name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write          # lets us push the tag
      id-token: write          # required for gh-release action

    steps:
    # ───── Setup ──────────────────────────────────────────────────────────
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    # ───── Extract version (needed for both image tagging & GH release) ───
    - name: Extract version from package.json
      id: version
      run: |
        VERSION=$(jq -r '.version' package.json)
        echo "Extracted version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_ENV

    # ───── Build & push Docker image (must succeed or job stops here) ─────
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64
        tags: |
          akatzai/comfydock-frontend:${{ env.version }}
          akatzai/comfydock-frontend:latest

    # ───── Publish tag ────────────────────────────────────────────────────
    - name: Create and push version tag
      if: success()
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git tag v${{ env.version }}
        git push origin v${{ env.version }}

    # ───── Create GitHub release ──────────────────────────────────────────
    - name: Create GitHub Release
      if: success()
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ env.version }}
        name: Release v${{ env.version }}
        draft: false
        prerelease: false
        generate_release_notes: true
